services:
  # Serwer bazy danych MySQL wykorzystujący Docker Secrets
  mysql:
    image: mysql:8.0.36
    container_name: lemp_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend
    secrets:
      - db_root_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Kontener procesora PHP (PHP-FPM)
  php:
    image: php:8.2-fpm-alpine
    container_name: lemp_php
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
    networks:
      - backend

  # Kontener serwera WWW (Nginx)
  nginx:
    image: nginx:1.25-alpine
    container_name: lemp_nginx
    restart: unless-stopped
    ports:
      - "4001:80"
    volumes:
      - ./html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend
      - backend
    depends_on:
      - php
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "80"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Kontener phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: lemp_phpmyadmin
    restart: unless-stopped
    ports:
      - "6001:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    networks:
      - backend
    depends_on:
      - mysql

networks:
  frontend:
    name: lemp_net_front
  backend:
    name: lemp_net_back

volumes:
  mysql_data:

# Definicja poziomu top-level dla sekretów aplikacji
secrets:
  db_root_password:
    file: ./db_root_password.txt